config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :contacts
  end
  
  resources :pitches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :submissions
  has_many :pitches, through: :submissions
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  has_many :submissions
  has_many :contacts, through: :submissions
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :contact
  belongs_to :pitch
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index

  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def index
    @pitches = Pitch.all
  end

  def show
    @pitch = Pitch.find(params[:id])
    @contacts = @pitch.contacts
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = Pitch.new(pitch_params)
    if @pitch.save
      redirect_to @pitch
    end
  end

  private

  def pitch_params
    params.require(:pitch).permit(:title, :body, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/show.html.erb
<header>
   <h1><span>contact</span>BOX</h1>
   <div class="form">
       <div class="info">
   <input class="input-field" type="text" placeholder="Contact Name" />
 </div>
   <div class="info">
   <input class="input-field" type="text" placeholder="Phone" /></div>
     <div class="info">
   <input class="input-field"type="text" placeholder="Email" /></div>
 <div class="info">
   <input class="input-field" type="text" placeholder="Location"/></div>
     <div class="info">
       <input class="input-field" type="text" placeholder="Type"/></div>
         <div class="info">
   <input class="input-field" type="text" placeholder="Date Last Contacted"/></div>
     <div class="info">
   <button id="save-btn" type="button">save</button>
 </div>
 </header>

   <input id="search-input" type="text" placeholder="Search" />

   <div class="contact-list">
     <div class="container">
       <h2 class="idea-title">Jonah Jameson</h2>
       <button class="delete-button"></button>
       <img src="https://files.slack.com/files-pri/T029P2S9M-F2CN45T52/jonah-jameson.jpg">
       <div class="info">
       <p class="contact-info">333-333-3333</p>

       <p class="contact-info">jjjameson@gmail.com</p>
 <p class="contact-info">Type: Editor</p>
       <p class="contact-info">Location: New York, NY</p>

       <p class="idea-body">Fields of Expertise</p>
       <p class="idea-body">Date Last Contact: 09/16/16</p>
       <p class="idea-body">Notes: Kind of snarky but, overall, a decent guy
y.  Really wants pictures of spiderman</p>
<button class="up-arrow"></button>
       <button class="down-arrow"></button>
       <p class="idea-quality">rating: 4</p>

       <p class="idea-body">Pitch Description</p>
       <p class="idea-body">Pitch Status</p>
       <p class="idea-quality">Pending</p>

       <div class="pitch-status"></div>
       <p class="idea-quality">Accepted</p>
     </div>
   </div>
   <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
   <script src="scripts.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackthenews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pitches/_form.html.erb
<h2>New Pitch</h2>

<%= form_for(@pitch) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br />
  <%= f.label :body %>
  <%= f.text_area :body %> <br />
  <%= f.label :status %>
  <%= f.text_field :status %> <br />
  <%= f.submit %>
<% end %>

app/views/pitches/edit.html.erb
<h2>Edit Pitch</h2>

<%= render partial: "form" %>

app/views/pitches/index.html.erb
<h2>All Pitches</h2>

<% @pitches.each do |pitch| %>
  <%= link_to pitch.title, pitch %>
<% end %>

app/views/pitches/new.html.erb
<h2>New Pitch</h2>

<%= form_for(@pitch) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br />
  <%= f.label :body %>
  <%= f.text_area :body %> <br />
  <%= f.label :status %>
  <%= f.text_field :status %> <br />
  <%= f.submit %>
<% end %>

app/views/pitches/show.html.erb
<h1>Pitch Details: <%= @pitch.title %></h1>

<p>
  <%= @pitch.body %>
</p>

<h6><%= @pitch.status %></h6>

<ul>
  <% @contacts.each do |contact| %>
    <%= link_to contact.name, user_contact_path(contact) %>
  <% end %>
</ul>